### ISSUE TITLE
Remove Debug Console Logs for Content and Privacy Compliance

### ISSUE THREAD

**Issue by FaizDev72** [FaizDev72/SkillNest-EdTech-Platform-MERNStack#2]
During the development of the website, several console.log() statements were added for debugging purposes to verify the proper execution of various features. However, these logs can potentially expose sensitive information or internal functioning details, leading to privacy concerns and security risks.

To ensure content protection, user privacy, and overall security, all console.log() statements should be removed or hidden in the production environment. Leaving them in place could create vulnerabilities or potholes for unauthorized access to internal processes and data.

*Acceptance Criteria:*
- Remove or disable all console.log() statements across the entire codebase.
- Ensure that no sensitive data is being logged or exposed via the console.
- Test and verify that the removal of the logs does not affect the functionality of the website.
- Optionally, implement a logging mechanism that provides essential information in a controlled and secure manner (e.g., logging errors or warnings without exposing sensitive data).

**Comment by idk-mr4tyunjay** [comment]
Hey @FaizDev72 , I'd like to work on this issue. Can you assign it to me?

**Comment by FaizDev72** [comment]
Assigned to @idk-mr4tyunjay please make a **Pull Request** within 48h

**Comment by FaizDev72** [comment]
Thanks for the contribution @idk-mr4tyunjay
